### ISSUE TITLE
Colors are not being loaded properly from save file

### ISSUE THREAD

**Issue by Diogo-Valadares** [Lramseyer/vaporview#52]
**Describe the bug**
After executing a "Save Vaporwave Settings" and then "Load Vaporwave Settings" the colors are sometimes loaded wrong, E.G. an orange signal goes back to the default color.

**To Reproduce**
1. Add signals
2. Set different colors
3. Save Vaporwave Settings
4. Load Vaporwave Settings

**Expected behavior**
The colors should not change after loading

**Screenshots**
Its really not consistent but one example

I saved like this:
![Image](https://github.com/user-attachments/assets/fc400b07-6250-4c54-b451-164ec0934f60)

The A bus wire color changes to cyan
![Image](https://github.com/user-attachments/assets/a167771c-fce9-4f59-b157-30dbd78ba2a5)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - vscode 1.98.1
 - Version 1.3.1

Additionally I think the display format also changes but I can't confirm that since it only happened once

**Comment by Lramseyer** [comment]
Do you know if this is a problem when you save the file, or when you load the file? Do you have the settings file you used for this example?

**Comment by Diogo-Valadares** [comment]
After saving, looking at the .json of the example below, the color index of the c_address is wrong so I'm guessing the problem is when I save the file.

```
{
  "netlistId": 160,
  "name": "test_drisc.drisc_processor.register_file_0.c_address",
  "numberFormat": "hexadecimal",
  "colorIndex": 0,
  "renderType": "multiBit"
},
{
  "netlistId": 59,
  "name": "test_drisc.drisc_processor.c_bus",
  "numberFormat": "hexadecimal",
  "colorIndex": 2,
  "renderType": "multiBit"
},
```

|Saved like this:|Loaded like this:|
|----------------|-----------------|
|![Image](https://github.com/user-attachments/assets/358413e1-8c73-444e-b6da-af6efa21500f)|![Image](https://github.com/user-attachments/assets/edb7881c-5aeb-4e29-b3fd-c4930e915ab3)|

save file:
[test.json](https://github.com/user-attachments/files/19229946/test.json)
vcd:
[dump.txt](https://github.com/user-attachments/files/19229953/dump.txt)

**Comment by Lramseyer** [comment]
OK first of all, excellent find and excellent debug work! This helps a ton!

I need to take a look at this tonight, but when loading in a save file it looks up the variables by path name _specifically_ so that it won't break if you change the circuit. So if it's breaking when you change your design (assuming path names of what's in the viewer don't change) then that defeats the purpose, and I need to fix that!

**Comment by Lramseyer** [comment]
OK, I think I fixed this in the latest commit. I was able to recreate the save file not saving off the color correctly, which I was able to fix. However, you also mentioned another issue, where when the circuit changes, things don't load correctly. I found what I believe to be the root cause of it and fixed it, but unfortunately, I don't have any test files to test that out on. So I'm going to need some help. I updated the [release](https://github.com/Lramseyer/vaporview/releases/tag/1.3.2-release-candidate) build to include these changes in case you want to try it out!

**Comment by Diogo-Valadares** [comment]
Well, that was quick! 
The saving seems to be fixed, but the loading is still broken

The files below should help you testing
Config file:
[test.json](https://github.com/user-attachments/files/19253131/test.json)

vcd that doesn't load correctly
[vcd.txt](https://github.com/user-attachments/files/19253138/vcd.txt)

vcd that loads correctly
[working_vcd.txt](https://github.com/user-attachments/files/19253190/working_vcd.txt)

**Comment by Lramseyer** [comment]
>but the loading is still broken

Are you referring to the issue where a different circuit has an incompatible save file? Or is the original issue of colors not loading correctly still an issue?

Also, I assume that the test.json was created from working_vcd.txt?

**Comment by Diogo-Valadares** [comment]
> Are you referring to the issue where a different circuit has an incompatible save file

Yes.

> Also, I assume that the test.json was created from working_vcd.txt?

Yes, the working_vcd was the one used to create the save file, and the vcd.txt is a modified version of this circuit. The signals being tracked are the same, so the colors and other info were supposed to load correctly but they aren't.

**Comment by Lramseyer** [comment]
Thanks for the test files! I was able to recreate the issue and fix it. I updated the [release](https://github.com/Lramseyer/vaporview/releases/tag/1.3.2-release-candidate) build again with this fix.

**Comment by Diogo-Valadares** [comment]
It does seem to be working properly now. At first it wasn't working and spent some minutes trying to find out what was wrong but I just had to restart VScode and now it works like a charm.

I'll keep testing and let you know if there is anything broken. 

Thanks for creating this wonderful extension!

**Comment by Lramseyer** [comment]
1.3.2 has been released. I'm going to close this issue if nobody is experiencing this issue anymore, but I will give it a few more days.

**Comment by victor-fisyuk** [comment]
Hi everyone,
I'm experiencing a similar issue where `numberFormat` and `renderType` break after loading saved settings whenever I add new signals to the modules (even in the latest version `1.4.1`).
Thank you.

<img width="1299" height="249" alt="Image" src="https://github.com/user-attachments/assets/5a8389ce-1afd-4f7a-b0a9-8d4e5f446e58" />

<img width="1319" height="247" alt="Image" src="https://github.com/user-attachments/assets/162e440c-984e-45b9-88f3-bad86b659a07" />

<img width="1033" height="860" alt="Image" src="https://github.com/user-attachments/assets/dbdb0be2-b5bc-406c-9c36-6b3da0796226" />
